### PR TITLE
Add a (primitive) implementation for setting parameter values to the iemic interface.

### PR DESCRIPTION
**Pull request by merijn**

### CODE REVIEW

**Comment by ipelupessy** [comment]
it also needs the underscore (set_u_ etc) versions...

**Comment by ipelupessy** [comment]
and also, the grid definitions need to know these:
```
    def define_grids(self, handler):
        #~ code_generator.generate_grid_definitions(object)

        # ocean dynamic variables p-grid: po, dpo_dt, vorticity
        handler.define_grid('grid',axes_names = ["lon", "lat"], grid_class=CartesianGrid)
        handler.set_grid_range('grid', '_grid_range')
        handler.add_getter('grid', 'get_real_pos', names=["lon", "lat", "z"])
        handler.add_getter('grid', 'get_u', names=["u_velocity"])
        handler.add_getter('grid', 'get_v', names=["v_velocity"])
        handler.add_getter('grid', 'get_w', names=["w_velocity"])
        handler.add_getter('grid', 'get_t', names=["temperature"])
        handler.add_getter('grid', 'get_s', names=["salinity"])
        handler.add_getter('grid', 'get_p', names=["pressure"])
        handler.add_setter('grid', 'set_u', names=["u_velocity"])
        handler.add_setter('grid', 'set_v', names=["v_velocity"])
        handler.add_setter('grid', 'set_w', names=["w_velocity"])
        handler.add_setter('grid', 'set_t', names=["temperature"])
        handler.add_setter('grid', 'set_s', names=["salinity"])
        handler.add_setter('grid', 'set_p', names=["pressure"])

        handler.add_getter('grid', 'get_land_mask', names=["mask"])
        

    def _specify_grid(self, definition, index=0):
        #~ handler.define_grid('grid',axes_names = ["lon", "lat"], grid_class=CartesianGrid)
        definition.axes_names=["lon", "lat"]
        definition.set_grid_range('_grid_range')
        definition.add_getter('get_real_pos', names=["lon", "lat", "z"])
        definition.add_getter('get_u_', names=["u_velocity"])
        definition.add_getter('get_v_', names=["v_velocity"])
        definition.add_getter('get_w_', names=["w_velocity"])
        definition.add_getter('get_t_', names=["temperature"])
        definition.add_getter('get_s_', names=["salinity"])
        definition.add_getter('get_p_', names=["pressure"])
        definition.add_getter('get_land_mask', names=["mask"])
        definition.add_setter('set_u_', names=["u_velocity"])
        definition.add_setter('set_v_', names=["v_velocity"])
        definition.add_setter('set_w_', names=["w_velocity"])
        definition.add_setter('set_t_', names=["temperature"])
        definition.add_setter('set_s_', names=["salinity"])
        definition.add_setter('set_p_', names=["pressure"])

        definition.define_extra_keywords({'sindex':index})


```

**Comment by ipelupessy** [comment]
for the underscore versions the oly tricky thing is the order of the parameters:
```
int32_t set_u_(int *i, int *j, int *k, double *var, int* sindex, int n)
{ return set_param(states[*sindex], Parameter::u, i, j, k, var, n); }
```

**Comment by ipelupessy** [comment]
I think you must swap the order of var and sindex arguments in the set_u_ etc (sindex is always added as keyword argument, while var may be positional)??

**Comment by ipelupessy** [comment]
this is only for the setters btw

**Comment by merijn** [comment]
Yeah, dumb copy paste error

**Pull request merged**
