### PR TITLE
Continuation test/implementation for I-EMIC

### PR DESCRIPTION
**Pull request by Sbte**

### CODE REVIEW

**Comment by ipelupessy** [comment]
looks good! just comment if its ready to merge...

**Comment by Sbte** [comment]
At least still depends on #25

**Comment by ipelupessy** [comment]
ok, but merijn suggests merging #24 first (in the PR)??

**Comment by Sbte** [comment]
Nah, I need to rebase and change the parameter handling anyway, so it's better to merge that first.

**Comment by ipelupessy** [comment]
ok

**Comment by ipelupessy** [comment]
#25 has been merged..

**Comment by Sbte** [comment]
Waiting for #26 now

**Comment by Sbte** [comment]
This should be ready now.

**Comment by merijn** [comment]
The rest looks good to me

**Comment by Sbte** [comment]
Doesn't work for me

**Comment by ipelupessy** [comment]
details?

**Comment by Sbte** [comment]
Details: The parameters don't actually change.

I don't understand handler transitions or when they occur, so no idea how to debug this.

I rebased the branch so you can see my test does not work.

**Pull request merged**
