### PR TITLE
added STORM class to hurricane models

### PR DESCRIPTION
**Pull request by ipelupessy**
this redoes #33 take 2

### CODE REVIEW

**Comment by ipelupessy** [comment]
@mchertova this is the cleaned up version of your PR #33..I think its ok, but can you check it includes all your changes?

**Comment by ipelupessy** [comment]
comment from #33 "Added STORM database filetype to the hurricane_models. Requires some attention in usage due to arbitrary selected starting year (Starting year in input files is 0.00 even for historic events)"

**Comment by mchertova** [comment]
@ipelupessy i've checked that, everything is there

**Comment by ipelupessy** [comment]
This does not include yet the radial wind correction, does it?

**Comment by mchertova** [comment]
yes, thats true, will have to correct for that

**Comment by ipelupessy** [comment]
will just merge this first...

**Pull request merged**
